# This is the example static network config for Netplan
network:
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.1.50/24]
      gateway4: 192.168.1.1
      nameservers:
       addresses: [192.168.1.1, 8.8.8.8]
  version: 2
